package com.nexus.entity;
public enum MotivoDevolucion {
    PRODUCTO_DEFECTUOSO, PRODUCTO_NO_CORRESPONDE,
    DANO_EN_TRANSPORTE, CAMBIO_DE_OPINION,
    TALLA_INCORRECTA, DOBLE_PEDIDO, VENDEDOR_CANCELACION, OTRO
}
