package com.nexus.entity;

public enum TipoNotificacion {
    NUEVO_MENSAJE,
    NUEVA_COMPRA,
    ESTADO_ENVIO,
    PEDIDO_ENVIADO,
    ENTREGA_CONFIRMADA,
    NUEVA_VALORACION,
    NUEVO_VOTO,
    DEVOLUCION_SOLICITADA,
    DEVOLUCION_ACEPTADA,
    DEVOLUCION_RECHAZADA,
    OFERTA_DESTACADA,
    SISTEMA
}