package com.nexus.entity;
public enum TipoNotificacion {
    NUEVO_MENSAJE, NUEVA_COMPRA,
    COMPRA_CONFIRMADA,
    ENVIO_ACTUALIZADO,
    NUEVA_VALORACION,
    SPARK_EN_OFERTA,
    NUEVO_COMENTARIO,
    DEVOLUCION,
    SISTEMA
}
